# https://semgrep.dev/docs/semgrep-ci/sample-ci-configs


# Name of this GitHub Actions workflow.
name: Semgrep CE scan

on:
  # Scan in PRs:
  pull_request: {}
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  # Scan mainline branches and report all findings:
  push:
    branches: ["master", "main"]

permissions:
  contents: read

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Install git in container
        run: |
          apt-get update
          apt-get install -y git

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 0 は全履歴（完全クローン）
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Ensure refs
        if: github.event_name == 'pull_request'
        run: |
          git fetch --no-tags origin ${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }} \
                                     ${{ github.head_ref }}:refs/remotes/origin/${{ github.head_ref }}

      - name: Compute changed files (NUL-delimited)
        id: diff
        run: |
          set -eu
          echo "inside git? $(git rev-parse --is-inside-work-tree || echo no)"

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE=$(git merge-base origin/${{ github.base_ref }} HEAD)
            git diff -z --name-only --diff-filter=d "$BASE"..HEAD > changed.nul

          elif [ "${{ github.event_name }}" = "push" ]; then
            # push: 受信レンジ全体
            git diff -z --name-only --diff-filter=d \
              "${{ github.event.before }}".."${{ github.sha }}" > changed.nul

          else
            # workflow_dispatch 等: フォールバック（例：main との差分）
            git fetch --no-tags origin main:refs/remotes/origin/main || true
            if git rev-parse --verify -q refs/remotes/origin/main >/dev/null; then
              BASE=$(git merge-base refs/remotes/origin/main HEAD)
              git diff -z --name-only --diff-filter=d "$BASE"..HEAD > changed.nul
            else
              # main が無い/単発実行ならフルスキャン
              git ls-files -z > changed.nul
            fi
          fi

          if [ -s changed.nul ]; then
            echo "has=true" >> "$GITHUB_OUTPUT"
            tr '\0' '\n' < changed.nul | head -20
            n=$(tr '\0' '\n' < changed.nul | wc -l)
            [ "$n" -gt 20 ] && echo "... and $((n-20)) more"
          else
            echo "has=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Semgrep (diff)
        if: steps.diff.outputs.has == 'true'
        run: |
          # semgrep/semgrep コンテナには Semgrep が入っています。pip インストール不要です。
          xargs -0 -r semgrep --config=auto < changed.nul
